tsuyoshicho/vim-efm-langserver-settings

- README.md
- config/efm-langserver/config.yaml
- config/efm-langserver/settings.json
> feat: add fixjson

- plugin/ale/efm_langserver_settings.vim
> Fix scope again

- after/plugin/ale/efm_langserver_settings.vim
- after/plugin/coc/efm_langserver_settings.vim
- after/plugin/lsp/efm_langserver_settings.vim
- autoload/efm_langserver_settings.vim
- doc/vim-efm-langserver-settings.jax
- doc/vim-efm-langserver-settings.txt
> feat: custom setting support

- config/efm-langserver/config.yaml
https://github.com/koalaman/shellcheck/wiki/SC2250
> fix: respect shellcheck default behavior

- config/efm-langserver/config.yaml
> fix: rubocop format cmdline

- config/efm-langserver/config.yaml
> feat: refactor

- config/efm-langserver/config.yaml
- fix some efm format string
- simplify
チェックボックス式にし、確認後チェックする。
> feat: Update errorformat

- config/efm-langserver/config.yaml
> fix: flake8 error code

- config/efm-langserver/config.yaml
close #117 
- flake8 code support plugins.
- error type detect remove
- error code number support
- catch up plugin error
> fix: flake8 error code include message

- after/plugin/coc/efm_langserver_settings.vim
> fix: behavior on coc.nvim

- config/efm-langserver/config.yaml
- config/efm-langserver/settings.json
buf is a lint tool for Protobol Buffer
https://buf.build/
> feat: Add buf support

- config/efm-langserver/config.yaml
none
- pylint root marker added.
none
- pylint just work root `.pylintrc`
> fix: config: pylint root marker added

- config/efm-langserver/config.yaml
- config/efm-langserver/settings.json
close #134 
- import efm-langserver example elixir credo lint
- test
- add support credo
(nothing)
> feat: add elixir credo lint

- config/efm-langserver/config.yaml
> feat: Add rubocop format

- config/efm-langserver/config.yaml
> fix: textlint: more fix stdin/file define

- config/efm-langserver/config.yaml
- config/efm-langserver/settings.json
Fix 2 point
- asciidoctor fix (old asciidoc)
- prettier action set to javascript
> fix: filetype etc

- config/efm-langserver/config.yaml
- config/efm-langserver/settings.json
> Revert "fix: replace asciidoc to asciidoctor"

- config/efm-langserver/config.yaml
rubocop fix safe/all
see https://koic.hatenablog.com/entry/rubocop-safe-autocorrect-by-default
> Update rubocop correct and add safe/all settings

- config/efm-langserver/config.yaml
> fix: Add prettier root marker and setup deno dual stack setup

- config/efm-langserver/config.yaml
> fix: update config for root marker
